import { v4 as uuid } from 'https://jspm.dev/uuid';

export const products = [
    {
      _id: 1,
      name: "Men checked Shirt",
      img:  "https://cdn.shopify.com/s/files/1/0420/7073/7058/files/4MSS2701-01-M1.jpg?v=1713439397&width=800",
      alt: "Mens checked Shirt",
      brand: "Snitch",
      newPrice: 1267,
      oldPrice: 2200,
      discount:18,
      size: "M",
      idealFor: "M",
      rating: 4.3
    },
    {
      _id: 2,
      name: "Men Tshirt",
      img: "https://cdn.shopify.com/s/files/1/0420/7073/7058/products/Snitch_14thJune21_0121-1.jpg?v=1626078058",
      alt: "Men Tshirt",
      brand: "Snitch",
      newPrice: 899,
      oldPrice: 1200,
      discount:30,
      size: "S",
      idealFor: "M",
      rating: 4.0
    },
    {
      _id: 3,
      name: "Girls Suit",
      img: "https://www.biba.in/dw/image/v2/BKQK_PRD/on/demandware.static/-/Sites-biba-product-catalog/default/dw440866f3/images/ss24/skdblackwhite9428ss24owht_1.jpg?sw=502&sh=753",
      alt: "Girls Suit",
      brand:"BIBA",
      newPrice: 6955,
      oldPrice: 10000,
      discount:40,
      size: "M",
      idealFor: "F",
      rating: 4.3
    },
    {
        _id: 4,
        name: "Girls Jeans",
        img: "https://th.bing.com/th?id=OPAC.A8EUQAyzdQ21Nw474C474&w=230&h=342&c=17&o=6&dpr=1.5&pid=21.1",
        alt: "Girls Jeans",
        brand: "Urbanic",
        newPrice: 1999,
        oldPrice: 3999,
        discount:50,
        size: "32",
        idealFor: "F",
        rating: 4.1
    },
    {
        _id: 5,
        name: "Girls Top",
        img: "https://m.media-amazon.com/images/I/41hLs+bBV1L.jpg",
        alt: "Girls Top",
        brand: "Istyle",
        newPrice: 499,
        oldPrice: 999,
        discount:50,
        size: "M",
        idealFor: "F",
        rating: 4
    },
    {
        _id: 6,
        name: "Rolex Watch",
        img: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcR56NRo8jGaKHEt5f7_LDce3LbethjUuHwP0DgBmfjHa58ySrWTP8lNmPf5ZmAi-GmMRfl66R4-NQmCfvRCOq7LIGmtDM40PP8xuCbeJJXC9SySiBGpYIlAhCdkmMB84ZMRsdMLEJM2DNM&usqp=CAc",
        alt: "Watch",
        brand:"Rolex",
        newPrice: 78000,
        oldPrice: 115000,
        discount:30,
        size: "Adjustable",
        idealFor: "M",
        rating: 4.9
    },
    {
        _id: 7,
        name: "Watch",
        img: "https://m.media-amazon.com/images/I/516GJfkO9-L._SY741_.jpg",
        alt: "Girls Watch",
        brand: "Acnos",
        newPrice: 499,
        oldPrice: 999,
        discount:50,
        size: "Adjustable",
        idealFor: "F",
        rating: 4.1
    },
    {
        _id: 8,
        name: "ASUS VIVOBOOK",
        img: "https://m.media-amazon.com/images/I/41rJ+ha25XL._SY300_SX300_.jpg", 
        alt: "Laptop",
        brand: "Asus",
        newPrice: 26990,
        oldPrice: 30000,
        discount:30,
        size: "32 inch",
        idealFor: "Everyday Use",
        rating: 4.5
    },
    {
        _id: 9,
        name: "Iphone 15",
        img: "https://m.media-amazon.com/images/I/71nvkHnPpZL._AC_UY327_FMwebp_QL65_.jpg",
        alt: "Iphone 15",
        brand: "Apple",
        newPrice: 71290,
        oldPrice: 80000,
        discount:18,
        size: "6 Inch", 
        idealFor: "Everyday",
        rating: 4.5
    },
    {
        _id: 10,
        name: "Boat Airpodes",
        img: "https://m.media-amazon.com/images/I/61KNJav3S9L.AC_SX500.jpg",
        alt: "Boat Airpodes",
        brand: "Boat",
        newPrice: 1699,
        oldPrice: 3990,
        discount:30,
        size: "Free Size",
        idealFor: "Everyday Use",
        rating: 4.5
    },
    {
        _id: 11,
        name: "Samsung LED",
        img: "https://m.media-amazon.com/images/I/71RxCmvnrbL._AC_UY327_FMwebp_QL65_.jpg",
        alt: "samsung LED",
        brand: "Samsung",
        newPrice: 14990,
        oldPrice: 22900,
        discount:35,
        size: "32 Inches",
        idealFor: "Everyday use",
        rating: 4.3
    },
    {
        _id: 12,
        name: "Canon EOS Camera",
        img: "https://m.media-amazon.com/images/I/81F3HiMFxdL._AC._SR360,460.jpg",
        alt: "Canon EOS Camera",
        brand: "Canon",
        newPrice: 79990,
        oldPrice: 92995,
        discount:30,
        size: "5 Inch",
        idealFor: "Photography",
        rating: 4.8
    },
    {
        _id: 13,
        name: "Wooden Sofa",
        img: "https://m.media-amazon.com/images/I/71iIElvimcL._AC_UL480_FMwebp_QL65_.jpg",
        alt: "Wooden Sofa",
        brand: "RATANDHARA FURNITURE",
        newPrice: 16999,
        oldPrice: 22000,
        discount:30,
        size: "6 Feet",
        idealFor: "Everyday Use",
        rating: 4.8
    },
    {
        _id: 14,
        name: "Modern Dining Table Set",
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSoByhaawFu5uE1gVxhLYuP31oLR2XUZL1qqQ&s",
        alt: "Modern Dining Table Set",
        brand: "Furny",
        newPrice: 22999,
        oldPrice: 28000,
        discount: 18,
        size: "4 Seater",
        idealFor: "Dining Room",
        rating: 4.5
    },
    {
        _id: 15,
        name: "Smart LED TV",
        img: "https://m.media-amazon.com/images/I/715Ukad5t4L._AC_UF1000,1000_QL80_.jpg",
        alt: "Smart LED TV",
        brand: "Samsung",
        newPrice: 39999,
        oldPrice: 45000,
        discount: 11,
        size: "55 Inches",
        idealFor: "Living Room",
        rating: 4.7
    },
    {
        _id: 16,
        name: "Laptop Backpack",
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRIQj9J0s1jnhkgKio8Lf_cDAOPGLxM9SHzFgETd8y5Sw&s",
        alt: "Laptop Backpack",
        brand: "Skybags",
        newPrice: 1699,
        oldPrice: 2000,
        discount: 15,
        size: "Medium",
        idealFor: "Travel",
        rating: 4.6
    },
    {
        _id: 17,
        name: "Wireless Earbuds",
        img: "https://www.sony.co.in/image/6ff70f66ce935f02861635b3e936a70c?fmt=pjpeg&wid=330&bgcolor=FFFFFF&bgc=FFFFFF",
        alt: "Wireless Earbuds",
        brand: "Boat",
        newPrice: 1999,
        oldPrice: 2500,
        discount: 20,
        size: "One Size",
        idealFor: "Music Lovers",
        rating: 4.4
    },
    {
        _id: 18,
        name: "Queen Size Bed",
        img: "https://elysiumstudio.in/wp-content/uploads/2023/02/untitled.1274_696x561.webp",
        alt: "Queen Size Bed",
        brand: "Wakefit",
        newPrice: 15999,
        oldPrice: 20000,
        discount: 20,
        size: "Queen",
        idealFor: "Bedroom",
        rating: 4.9
    },
    {
        _id: 19,
        name: "Digital Camera",
        img: "https://i.pcmag.com/imagery/reviews/03lo9RsLzRw3txoeExNaEHW-38..v1574731241.jpg",
        alt: "Digital Camera",
        brand: "Canon",
        newPrice: 24999,
        oldPrice: 30000,
        discount: 17,
        size: "One Size",
        idealFor: "Photography Enthusiasts",
        rating: 4.6
    },
    {
        _id: 20,
        name: "Fitness Tracker Watch",
        img: "https://m.media-amazon.com/images/I/61YwaovfYFL.jpg",
        alt: "Fitness Tracker Watch",
        brand: "Fitbit",
        newPrice: 3999,
        oldPrice: 5000,
        discount: 20,
        size: "One Size",
        idealFor: "Fitness Enthusiasts",
        rating: 4.7
    },
    {
        _id: 21,
        name: "Gaming Console",
        img: "https://www.livemint.com/lm-img/img/2024/04/29/600x338/pexels-jeshoots-com-147458-442576_1714388557344_1714388564716.jpg",
        alt: "Gaming Console",
        brand: "Sony PlayStation",
        newPrice: 29999,
        oldPrice: 35000,
        discount: 14,
        size: "One Size",
        idealFor: "Gamers",
        rating: 4.8
    },
    {
        _id: 22,
        name: "Electric Kettle",
        img: "https://dailydeals365.in/wp-content/uploads/2023/02/713MGnrit2S._SL1500_.jpg",
        alt: "Electric Kettle",
        brand: "Prestige",
        newPrice: 999,
        oldPrice: 1200,
        discount: 17,
        size: "1.5 Litres",
        idealFor: "Kitchen",
        rating: 4.5
    },
    {
        _id: 23,
        name: "Portable Bluetooth Speaker",
        img: "https://mm.jbl.com/dw/image/v2/AAUJ_PRD/on/demandware.static/-/Sites-masterCatalog_Harman/default/dw82d500db/JBL_Clip2_Black_Hero_x1-1606x1606px_dvHAMaster.png?sw=537&sfrm=png",
        alt: "Portable Bluetooth Speaker",
        brand: "JBL",
        newPrice: 2499,
        oldPrice: 3000,
        discount: 17,
        size: "One Size",
        idealFor: "Music Lovers",
        rating: 4.7
    },
    {
        _id: 24,
        name: "Air Purifier",
        img: "https://nirvanabeing.com/cdn/shop/files/KJ750F-01A_1600x.jpg?v=1699527212",
        alt: "Air Purifier",
        brand: "Mi",
        newPrice: 7999,
        oldPrice: 10000,
        discount: 20,
        size: "Medium",
        idealFor: "Home",
        rating: 4.6
    }
]

